CREATE TABLE CONTENEDOR (
                            ID_CONTENEDOR NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            LOCALIZACAO VARCHAR2(100),
                            CAPACIDADE_LITROS FLOAT(53),
                            TIPO_MATERIAL VARCHAR2(50)
);

CREATE TABLE ROTA (
                      ID_ROTA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      VEICULO VARCHAR2(100),
                      ENDERECO_BASE VARCHAR2(100),
                      CAPACIDADE FLOAT(53)
);

CREATE TABLE LEITURA (
                         ID_LEITURA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         ID_CONTENEDOR NUMBER,
                         DATA_HORA DATE,
                         NIVEL_PERCENT FLOAT(53),
                         PESO_KG FLOAT(53),
                         CONSTRAINT FK_LEITURA_CONTENEDOR FOREIGN KEY (ID_CONTENEDOR)
                             REFERENCES CONTENEDOR (ID_CONTENEDOR)
);

CREATE TABLE COLETA (
                        ID_COLETA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ID_CONTENEDOR NUMBER,
                        DATA_AGENDADA DATE,
                        STATUS VARCHAR2(100),
                        ID_ROTA NUMBER,
                        CONSTRAINT FK_COLETA_CONTENEDOR FOREIGN KEY (ID_CONTENEDOR)
                            REFERENCES CONTENEDOR (ID_CONTENEDOR),
                        CONSTRAINT FK_COLETA_ROTA FOREIGN KEY (ID_ROTA)
                            REFERENCES ROTA (ID_ROTA)
);

CREATE TABLE DESTINACAO (
                            ID_DESTINACAO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            TIPO_MATERIAL VARCHAR2(50),
                            LOCAL_DESTINO VARCHAR2(100),
                            DATA_REGISTRO DATE,
                            QUANTIDADE_KG FLOAT(53)
);
