INSERT INTO CONTENEDOR (LOCALIZACAO, CAPACIDADE_LITROS, TIPO_MATERIAL)
VALUES ('Rua das Palmeiras, 120', 1000.0, 'Plástico');

INSERT INTO CONTENEDOR (LOCALIZACAO, CAPACIDADE_LITROS, TIPO_MATERIAL)
VALUES ('Avenida Central, 500', 800.0, 'Vidro');

INSERT INTO CONTENEDOR (LOCALIZACAO, CAPACIDADE_LITROS, TIPO_MATERIAL)
VALUES ('Praça Verde, 45', 1200.0, 'Papel');

INSERT INTO CONTENEDOR (LOCALIZACAO, CAPACIDADE_LITROS, TIPO_MATERIAL)
VALUES ('Rua dos Ipês, 210', 1500.0, 'Metal');

INSERT INTO CONTENEDOR (LOCALIZACAO, CAPACIDADE_LITROS, TIPO_MATERIAL)
VALUES ('Rua do Comércio, 320', 900.0, 'Orgânico');