INSERT INTO ROTA (VEICULO, ENDERECO_BASE, CAPACIDADE)
VALUES ('Caminhão 01', 'Garagem Zona Norte', 5000.0);

INSERT INTO ROTA (VEICULO, ENDERECO_BASE, CAPACIDADE)
VALUES ('Caminhão 02', 'Garagem Zona Sul', 4500.0);

INSERT INTO ROTA (VEICULO, ENDERECO_BASE, CAPACIDADE)
VALUES ('Caminhão 03', 'Garagem Zona Leste', 4800.0);

INSERT INTO ROTA (VEICULO, ENDERECO_BASE, CAPACIDADE)
VALUES ('Caminhão 04', 'Garagem Zona Oeste', 4600.0);

INSERT INTO ROTA (VEICULO, ENDERECO_BASE, CAPACIDADE)
VALUES ('Caminhão 05', 'Garagem Central', 5500.0);