INSERT INTO DESTINACAO (TIPO_MATERIAL, LOCAL_DESTINO, DATA_REGISTRO, QUANTIDADE_KG)
VALUES ('Plástico', 'Recicladora Zona Norte', TO_DATE('2025-11-05', 'YYYY-MM-DD'), 450.0);

INSERT INTO DESTINACAO (TIPO_MATERIAL, LOCAL_DESTINO, DATA_REGISTRO, QUANTIDADE_KG)
VALUES ('Vidro', 'Recicladora Central', TO_DATE('2025-11-05', 'YYYY-MM-DD'), 280.0);

INSERT INTO DESTINACAO (TIPO_MATERIAL, LOCAL_DESTINO, DATA_REGISTRO, QUANTIDADE_KG)
VALUES ('Papel', 'Recicladora Zona Sul', TO_DATE('2025-11-05', 'YYYY-MM-DD'), 520.0);

INSERT INTO DESTINACAO (TIPO_MATERIAL, LOCAL_DESTINO, DATA_REGISTRO, QUANTIDADE_KG)
VALUES ('Metal', 'Recicladora Industrial', TO_DATE('2025-11-05', 'YYYY-MM-DD'), 400.0);

INSERT INTO DESTINACAO (TIPO_MATERIAL, LOCAL_DESTINO, DATA_REGISTRO, QUANTIDADE_KG)
VALUES ('Orgânico', 'Compostagem Central', TO_DATE('2025-11-05', 'YYYY-MM-DD'), 550.0);
